// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbrCK2iWkFgCitn3QgG3P2TZvUIBNpkGg',
    appId: '1:674885983930:web:6206fada19f98799f02c83',
    messagingSenderId: '674885983930',
    projectId: 'ecommerceapp-a654a',
    authDomain: 'ecommerceapp-a654a.firebaseapp.com',
    storageBucket: 'ecommerceapp-a654a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUq6uyYqdCvYs1cPby5mdHiZn4OX1Lo5M',
    appId: '1:674885983930:android:e462556fd556b6c3f02c83',
    messagingSenderId: '674885983930',
    projectId: 'ecommerceapp-a654a',
    storageBucket: 'ecommerceapp-a654a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk6qCUDs3oO4D4WIZtfZKCVk5ez7YBdVw',
    appId: '1:674885983930:ios:c7f2299b986ef3f7f02c83',
    messagingSenderId: '674885983930',
    projectId: 'ecommerceapp-a654a',
    storageBucket: 'ecommerceapp-a654a.appspot.com',
    androidClientId: '674885983930-vpft8e0abmnar4vrljt8d0p02uspa91j.apps.googleusercontent.com',
    iosClientId: '674885983930-r60rq40m7gdk4hqmdkdc5hae6jd32ri4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
